name: Node.js CI

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14.x'
    - name: install deps
      run: |
          make install
      env:
        CI: true
    - name: Run linter
      run: |
          make lint
    - name: Run tests
      run: |
          make test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TOKEN }}
      with:
        coverageCommand: |
           make test coverage
        debug: true
